cours_python/BaseRestaurant/BaseRestaurant/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
    path('aperitif/', include('aperitif.urls')),
    path('vin/', include('vin.urls')),
    path('digestif/', include('digestif.urls')),
    path('', include('main.urls')),


]

cours_python/BaseRestaurant/aperitif/urls.py
from django.urls import path
from . import views



app_name = 'aperitif'
urlpatterns = [
    path('', views.index,name="index"),
]

cours_python/BaseRestaurant/digestif/urls.py
from django.urls import path
from . import views
app_name = 'digestif'
urlpatterns = [
    path('', views.index,name="index"),
]

cours_python/BaseRestaurant/main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('', views.index,name="index"),
]

cours_python/BaseRestaurant/menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name="index"),

]

cours_python/BaseRestaurant/vin/urls.py
from django.urls import path
from . import views
app_name = 'vin'
urlpatterns = [
    path('', views.index,name="index"),
]

cours_python/BaseRestaurant/aperitif/models.py
from django.db import models

class CommonInfo(models.Model):
    nom = models.CharField(max_length=100)
    prix = models.FloatField(default=0)
    ingredient = models.CharField(max_length=200, blank=True)

    class Meta:
        abstract = True
    def __str__(self):
        return self.nom


class Tapa(CommonInfo):
    pass
class Champagne(CommonInfo):
    pass
class Cocktail (CommonInfo):
    pass
class Classique(CommonInfo):
    pass
class CocktailClassique(CommonInfo):
    pass
class SansAlcools(CommonInfo):
    pass
class Vodka(CommonInfo):
    pass
class Gin (CommonInfo):
    pass
class Whiskie(CommonInfo):
    pass

cours_python/BaseRestaurant/digestif/models.py
from django.db import models


class Rhum(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origine_vin = models.CharField(max_length=200,blank=True)



class Armagnac(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origine_vin = models.CharField( max_length=200,blank=True)



class Calvados(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origine_vin = models.CharField(max_length=200, blank=True)

class Cognac(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origine_vin = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.nom

cours_python/BaseRestaurant/main/models.py
from django.db import models

cours_python/BaseRestaurant/menu/models.py
from django.db import (models)


class Entree(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origin_viande = models.CharField(max_length=200,blank=True)
    commentaire = models.CharField(max_length=200, blank=True)


class Plat(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origin_viande = models.CharField( max_length=200,blank=True)
    commentaire = models.CharField(max_length=200, blank=True)


class Suggestion_Plat(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origin_viande = models.CharField(max_length=200, blank=True)
    commentaire = models.CharField(max_length=200,blank=True)




class Dessert(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origin_viande = models.CharField(max_length=200, blank=True)
    commentaire = models.CharField(max_length=200, blank=True)


class PrixMenuEnfant(models.Model):
    nom_et_ou_prix = models.CharField(max_length=200, blank=True)
    prix = models.FloatField(default=0)
    origin_viande = models.CharField(max_length=200, blank=True)
    commentaire = models.CharField(max_length=200, blank=True)


class PlatMenuEnfant(models.Model):
    nom_et_ou_prix = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origin_viande = models.CharField(max_length=200, blank=True)
    commentaire = models.CharField(max_length=200, blank=True)

class DessertEnfant(models.Model):
    nom_et_ou_prix = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origin_viande = models.CharField(max_length=200, blank=True)
    commentaire = models.CharField(max_length=200, blank=True)

cours_python/BaseRestaurant/vin/models.py
from django.db import models


class VinRouge(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origine_vin = models.CharField(max_length=200,blank=True)



class VinBlanc(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origine_vin = models.CharField( max_length=200,blank=True)



class VinRosee(models.Model):
    nom = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    origine_vin = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.nom

cours_python/BaseRestaurant/aperitif/views.py
from django.shortcuts import render
from .models import Tapa,Champagne,Cocktail,Classique,CocktailClassique,SansAlcools,Vodka,Gin, Whiskie

def index(request):
    Tapas=Tapa.objects.all()
    Champagnes=Champagne.objects.all()
    Cocktails=Cocktail.objects.all()
    Classiques=Classique.objects.all()
    CocktailClassiques=CocktailClassique.objects.all()
    SansAlcoolss=SansAlcools.objects.all()
    Vodkas=Vodka.objects.all()
    Gins=Gin.objects.all()
    Whiskies=Whiskie.objects.all()

    return render(request, 'aperitif/index.html', {'Tapas': Tapas, 'Champagnes': Champagnes,
                                               'Cocktails': Cocktails, 'Classiques': Classiques,
                                               'CocktailClassiques': CocktailClassiques
                                                ,'SansAlcoolss': SansAlcoolss
                                                , 'Vodkas': Vodkas
                                                , 'Gins': Gins
                                                ,'Whiskies': Whiskies,})

cours_python/BaseRestaurant/digestif/views.py
from django.shortcuts import render

from .models import Rhum,Armagnac,Calvados,Cognac
def index(request):
    Rhums=Rhum.objects.all()
    Armagnacs=Armagnac.objects.all()
    Calvadoss=Calvados.objects.all()
    Cognacs = Cognac.objects.all()

    return render(request, 'digestif/index.html', {'Rhums': Rhums, 'Armagnacs': Armagnacs,
                                                   'Calvadoss': Calvadoss,'Cognacs': Cognacs})

cours_python/BaseRestaurant/main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html')

cours_python/BaseRestaurant/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from .models import Entree
from .models import Plat
from .models import Suggestion_Plat
from .models import Dessert
from .models import PlatMenuEnfant
from .models import PrixMenuEnfant
from .models import DessertEnfant




def index(request):
    entrees = Entree.objects.all()
    plats = Plat.objects.all()
    suggestions_plats = Suggestion_Plat.objects.all()
    desserts = Dessert.objects.all()
    plats_enfants = PlatMenuEnfant.objects.all()
    prix_enfants = PrixMenuEnfant.objects.all()
    desserts_enfants = DessertEnfant.objects.all()
    sections = (("Entrées: ", entrees), ("Plats: ", plats))


    return render(request, 'menu/index.html',{'entrees':entrees,'plats':plats,
                                              'suggestions_plats':suggestions_plats,'desserts':desserts,
                                              'plats_enfants':plats_enfants
                                              ,'prix_enfants':prix_enfants,
                                              "desserts_enfants":desserts_enfants})



def api_get_entree(request):
    entrees = Entree.objects.all()
    json = serializers.serialize("json",entrees)
    return HttpResponse(json)

cours_python/BaseRestaurant/vin/views.py
from django.shortcuts import render

from .models import VinRouge,VinBlanc,VinRosee
def index(request):
    VinRouges=VinRouge.objects.all()
    VinBlancs=VinBlanc.objects.all()
    VinRosees=VinRosee.objects.all()

    return render(request, 'vin/index.html', {'VinRouges': VinRouges, 'VinBlancs': VinBlancs,
                                                   'VinRosees': VinRosees})

cours_python/BaseRestaurant/digestif/templates/digestif/index.html
{% load static %}
<html lang="fr">
    <head>
        <title>Menu Restaurant</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'digestif/style.css'%}">
    </head>
    <body>
      <h1>Le  Restaurant</h1>
      <div>
            <img class="logo" src=" {% static 'digestif/images/restaurant_orange.png' %}">
      </div>
      <div class="separateur"></div>
      <div class="ensemble">

            <div class="section">
                <h2>Rhum</h2>
                {% for rhum in Rhums %}
                <div  class="separateur_2"></div>
                <span class="nom">{{rhum.nom }}</span>
                <span class="prix"> {{rhum.prix |floatformat:2}}€</span>
                <span class="commentaire">{{rhum.ingredient }}</span>
                  {%endfor%}
            </div>

            <div class="section">
                <h2>Armagnacs</h2>
                {% for armagnac in Armagnacs %}
                <div  class="separateur_2"></div>
                <span class="nom">{{armagnac.nom }}</span>
                <span class="prix"> {{armagnac.prix |floatformat:2}}€</span>
                <span class="commentaire">{{armagnac.ingredient }}</span>
                  {%endfor%}
            </div>

             <div class="section">
                <h2>Calvados</h2>
                {% for calvados in Calvadoss %}
                <div  class="separateur_2"></div>
                <span class="nom">{{calvados.nom }}</span>
                <span class="prix"> {{calvados.prix |floatformat:2}}€</span>
                <span class="commentaire">{{calvados.ingredient }}</span>
                  {%endfor%}
            </div>

            <div class="section_bottom">
                <h2>Cognacs</h2>
                {% for cognac in Cognacs %}
                <div  class="separateur_2"></div>
                <span class="nom">{{cognac.nom }}</span>
                <span class="prix"> {{cognac.prix |floatformat:2}}€</span>
                <span class="commentaire">{{cognac.ingredient }}</span>
                  {%endfor%}
            </div>
    </div>
            <div class="frame_position">
                    <a href="{% url 'main:index' %}"> Infos</a>
                    <a href="{% url 'menu:index' %}"> menu</a>
                    <a href="{% url 'aperitif:index' %}"> Apéritifs</a>
                    <a href="{% url 'vin:index' %}"> Vins</a>
                    <a href="{% url 'digestif:index' %}"> Digestifs</a>
            </div>


    </body>
</html>